/**
 * Theme interface and home theme definition.
 * Per-game themes live in games/{game-id}/theme.ts.
 * The themeMap is auto-generated by scripts/generate-theme-map.js.
 */

export interface Theme {
    colors: {
        background: string;
        card: string;
        cardAlt?: string;
        text: string;
        textMuted: string;
        accent: string;
        accentLight?: string;
        border?: string;
        parchment?: string;
    };
    fonts: {
        body: string;
        heading: string;
    };
    spacing: {
        sectionMargin: number;
        cardPadding: number;
        containerPadding: number;
    };
}

export const homeTheme: Theme = {
    colors: {
        background: '#1a1a2e',
        card: '#2a2a4e',
        text: '#e0e0e0',
        textMuted: '#a0a0b0',
        accent: '#6c63ff',
    },
    fonts: { body: 'System', heading: 'System' },
    spacing: { sectionMargin: 24, cardPadding: 20, containerPadding: 16 },
};
